### ISSUE TITLE
Exercise2_Error in Defined Variable

### ISSUE THREAD

**Issue by kristinakostopoulos** [InseadDataAnalytics/INSEADAnalytics#11]
In GAReport.Rmd line 68 variable "entrpmonthyear" does not exist in global environment creating an error when generating plot

**Comment by tevgeniou** [comment]
what file is this? link to it?

**Comment by kristinakostopoulos** [comment]
https://github.com/hezumartin/BDACaseStudyGA/tree/master/doc

**Comment by tevgeniou** [comment]
as explained in the files of the project (e.g. lie 44 of https://github.com/hezumartin/BDACaseStudyGA/blob/master/RunStudy.R ) one needs a google analytics account to use this code with tokens, websites, etc. Alternatively you should comment out these lines using a "#" at the beginning of each line:

55-58:
# client.id <- "{copy paste your Client ID here}"
# client.secret <- "{copy paste your Client secret here}"
# token <- Auth(client.id,client.secret)
# ValidateToken(token)

68:
# table.id <- "{copy paste your View ID here}"

72-72
#start.date  <-  "{Start date of the data}"
#end.date  <-  "{End date of the data}"

and try running the RunStudy.R code line by line first (please also check the directory paths).

**Comment by hezumartin** [comment]
Hi Kristina,

This should not prevent you from creating the report, it just shows an error instead of a plot. Nevertheless, I have updated the file to avoid this error, my mistake.

Thanks for the patience :)

Jesús

**Comment by tevgeniou** [comment]
indeed there was a bug: entrpmonthyear was not defined
see solutions, fixed that, too
https://github.com/tevgeniou/BDACaseStudyGA 
(hope no bug - but focus on idea)
