### ISSUE TITLE
BDACaseStudyGA

### ISSUE THREAD

**Issue by mrlajoie** [InseadDataAnalytics/INSEADAnalytics#12]
Following Kristina's error on that case, I attempted to modify the coding to : ggplot(entrpyear,aes(x = year, y = entrances)) + geom_bar(stat="identity", fill = "lightblue", colour = "black"). But got the following error (see image). Although it says it cannot find the gvisTable command, I clearly have uploaded the required package and found it. 
[GA eval problem 20160119.pdf](https://github.com/InseadDataAnalytics/INSEADAnalytics/files/95696/GA.eval.problem.20160119.pdf)

**Comment by tevgeniou** [comment]
see answer also in #10 and #11 
you need to install devotools etc e.g. http://slidify.org/start.html  and http://shiny.rstudio.com/articles/shinyapps.html 
and also install the package googleVis

**Comment by tevgeniou** [comment]
committed solutions, see 
https://github.com/tevgeniou/BDACaseStudyGA 
(hope no bug - but focus on idea)
