### ISSUE TITLE
Github fork doesn't sync with master

### ISSUE THREAD

**Issue by Marcusan** [InseadDataAnalytics/INSEADAnalytics#15]
I've forked the master repository "InseadDataAnalytics/INSEADAnalytics" which became "Marcusan/INSEADAnalytics" which I pulled into RStudio. However, my branch doesn't have the latest updates and additions to the master branch (those that were done after the initial forking).

How can I sync my repository so that the additions get reflected on my branch? On the print screen below, you'll notice that my branch has only 131 commits (master has 135 now) with the latest dating back a week (the latest on the master is from a few hours ago). 

![problem jan 19](https://cloud.githubusercontent.com/assets/16314727/12423127/42351f80-beca-11e5-97ad-25ff667f461d.jpg)

**Comment by tevgeniou** [comment]
see issue #7 
Don't repeat issues.
