### ISSUE TITLE
Failed to install 'ggthemr'

### ISSUE THREAD

**Issue by pedrofigueiredoaparicio** [InseadDataAnalytics/INSEADAnalytics#166]
When knitting 'ClassificationProcessCreditCardDefault.Rmd', received error:

Line 21 Error: Failed to install 'ggthemr' from GitHub: (converted from warning) cannot remove prior installation of package 'rlang'

**Comment by VarunKShetty** [comment]
Hi,

Can you please try and follow the latest instructions that Spyros emailed? You should be able to find it in the class announcements section as well. That should bypass this problem. Please post a response here otherwise and we can work through it.

-Varun.




On Feb 7, 2020 18:18, pedrofigueiredoaparicio <notifications@github.com> wrote:

When knitting 'ClassificationProcessCreditCardDefault.Rmd', received error:

Line 21 Error: Failed to install 'ggthemr' from GitHub: (converted from warning) cannot remove prior installation of package 'rlang'

**Comment by pedrofigueiredoaparicio** [comment]
Hi Varun,

I have followed Spyros' instructions, including the previous local repository and forking the GitHub rep again in my machine. Now, I get a different error, this time related to the package 'rlang':

> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called 'rlang'
> Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
> Execution halted

Can you please advise?
Thank you,
Pedro

**Comment by VarunKShetty** [comment]
Hi Pedro,

Can you try to install "rlang" directly from the console?

>install.packages("rlang")

From your console. And then try to knit again?

Please let me know how it works out.

Best,
Varun

Sent from my mobile. Please excuse brevity and typos.

On Feb 10, 2020 13:37, pedrofigueiredoaparicio <notifications@github.com> wrote:

Hi Varun,

I have followed Spyros' instructions, including the previous local repository and forking the GitHub rep again in my machine. Now, I get a different error, this time related to the package 'rlang':

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
there is no package called 'rlang'
Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

Can you please advise?
Thank you,
Pedro

**Comment by pedrofigueiredoaparicio** [comment]
Varun,
I believe the knitting has concluded well - at least, an html file ('MarketSegmentationProcessInClass.html') resulted, without execution being halted at any point.
Good to go, right?
Cheers,
Pedro

**Comment by VarunKShetty** [comment]
Yes. Good to go!

Can you please just check that the html is not blank?

Best,
Varun

Sent from my mobile. Please excuse brevity and typos.

On Feb 10, 2020 13:50, pedrofigueiredoaparicio <notifications@github.com> wrote:

Varun,
I believe the knitting has concluded well - at least, an html file ('MarketSegmentationProcessInClass.html') resulted, without execution being halted at any point.
Good to go, right?
Cheers,
Pedro

**Comment by pedrofigueiredoaparicio** [comment]
It is not, all seems good - thanks!
