### ISSUE TITLE
ExerciseSet2_Problem evaluating googleVis functions

### ISSUE THREAD

**Issue by gillesalex07** [InseadDataAnalytics/INSEADAnalytics#17]
I've installed the googleVis package, retrieved credentials from Google API website, and got authentification confirmation from the console as described in issue #12. 

However, when knitting ExerciseSet2.Rmd in html, I end up with a report that only shows the code, not the tables / charts. If I run lines 74-75 from the console, I get this:

<script type="text/javascript">
 
// jsData 
function gvisDataTableID313426155999 () {
var data = new google.visualization.DataTable();
var datajson =
[
 [
 "Corn" 
],
[
 "Wheat" 
],
[
 "Soybeans" 
],
[
 "Soybean Oil" 
],
[
 "Soybean Meal" 
],
[
 "Lean Hoggs" 
],
[
 "Sugar" 
],
[
 "Coffee" 
],
[
 "Cocoa" 
],
[
 "Cotton" 
],
[
 "Canola" 
],
[
 "Orange Juice" 
],
[
 "Lumber" 
],
[
 "Natural Gas" 
],
[
 "Crude Oil" 
],
[
 "Brent Crude" 
],
[
 "Heating Oil" 
],
[
 "Kerosene" 
],
[
 "Gas Oil" 
],
[
 "Gasoline" 
],
[
 "Copper NY" 
],
[
 "Copper LDN" 
],
[
 "Silver" 
],
[
 "Gold" 
],
[
 "Platinum" 
],
[
 "Palladium" 
],
[
 "Aluminium" 
],
[
 "Zinc" 
],
[
 "Nickel" 
],
[
 "Treasury Bonds" 
],
[
 "5 yr T-Notes US" 
],
[
 "2 yr T-Note US" 
],
[
 "10yr T-Notes" 
],
[
 "Euro-Bund" 
],
[
 "Euro-Bobl" 
],
[
 "Euro-Schatz" 
],
[
 "Canadian Bond" 
],
[
 "JGB Japan" 
],
[
 "Gilts UK" 
],
[
 "Euroyen" 
],
[
 "Eurodollar" 
],
[
 "Euroswiss" 
],
[
 "Euribor" 
],
[
 "SP500 E-Mini" 
],
[
 "DAX 30" 
],
[
 "Eurostoxx" 
],
[
 "Hang Seng" 
],
[
 "FTSE 100 UK" 
],
[
 "Nasdaq 100 Mini" 
],
[
 "Russel 2000 E-Mini" 
],
[
 "Dow Jones" 
],
[
 "TSE Toronto" 
],
[
 "CAC 40 France" 
],
[
 "OMX 30 Stockholm" 
],
[
 "NIKKEI 225" 
],
[
 "Euro" 
],
[
 "Norwegian Krone" 
],
[
 "New Zealand Dollar" 
],
[
 "Australian Dollar" 
],
[
 "British Pound" 
],
[
 "Canadian Dollar" 
],
[
 "Swiss Franc" 
],
[
 "Japanese Yen" 
],
[
 "Singapore Dollar" 
] 
];
data.addColumn('string','colnames.futures_data.');
data.addRows(datajson);
return(data);
}
 
// jsDrawChart
function drawChartTableID313426155999() {
var data = gvisDataTableID313426155999();
var options = {};
options["allowHtml"] = true;
options["showRowNumber"] = true;
options["width"] =   1920;
options["height"] =    400;
options["allowHTML"] = true;
options["page"] = "disable";

    var chart = new google.visualization.Table(
    document.getElementById('TableID313426155999')
    );
    chart.draw(data,options);
    

}
  
 
// jsDisplayChart
(function() {
var pkgs = window.__gvisPackages = window.__gvisPackages || [];
var callbacks = window.__gvisCallbacks = window.__gvisCallbacks || [];
var chartid = "table";
  
// Manually see if chartid is in pkgs (not all browsers support Array.indexOf)
var i, newPackage = true;
for (i = 0; newPackage && i < pkgs.length; i++) {
if (pkgs[i] === chartid)
newPackage = false;
}
if (newPackage)
  pkgs.push(chartid);
  
// Add the drawChart function to the global list of callbacks
callbacks.push(drawChartTableID313426155999);
})();
function displayChartTableID313426155999() {
  var pkgs = window.__gvisPackages = window.__gvisPackages || [];
  var callbacks = window.__gvisCallbacks = window.__gvisCallbacks || [];
  window.clearTimeout(window.__gvisLoad);
  // The timeout is set to 100 because otherwise the container div we are
  // targeting might not be part of the document yet
  window.__gvisLoad = setTimeout(function() {
  var pkgCount = pkgs.length;
  google.load("visualization", "1", { packages:pkgs, callback: function() {
  if (pkgCount != pkgs.length) {
  // Race condition where another setTimeout call snuck in after us; if
  // that call added a package, we must not shift its callback
  return;
}
while (callbacks.length > 0)
callbacks.shift()();
} });
}, 100);
}
 
// jsFooter
</script>
 
  
<script type="text/javascript" src="https://www.google.com/jsapi?callback=displayChartTableID313426155999"></script>
 

  
<div id="TableID313426155999" 
  style="width: 1920; height: 400;">
</div>

**Comment by tevgeniou** [comment]
image missing

**Comment by gillesalex07** [comment]
![image](https://cloud.githubusercontent.com/assets/16525387/12433210/03c01706-bf00-11e5-831b-3c5105091ff6.png)

![image](https://cloud.githubusercontent.com/assets/16525387/12433221/1872c2fc-bf00-11e5-80ad-077f689c0d49.png)

**Comment by tevgeniou** [comment]
hmm, can't see anything wrong from this. curious to see what the problem could be. maybe open the html file created using another browser? maybe try some simpler examples from the internet first?

**Comment by gillesalex07** [comment]
When I replace print(m1, 'chart') with plot(m1) in Line 75, a web browser pops up and the table is properly displayed. So it seems that the problem is not with googleVis but with R.

**Comment by gillesalex07** [comment]
We can work around this issue by opening the html report from the "files" tab in RStudio. Just click on the file and select "open in we browser" as depicted below.

![image](https://cloud.githubusercontent.com/assets/16525387/12486286/41b19c8e-c062-11e5-924b-bb80d8291089.png)
