### ISSUE TITLE
ExerciseSet2 - quandl not opening

### ISSUE THREAD

**Issue by mrlajoie** [InseadDataAnalytics/INSEADAnalytics#19]
See error message. 
[quandl not opening.pdf](https://github.com/InseadDataAnalytics/INSEADAnalytics/files/98195/quandl.not.opening.pdf)

**Comment by LiLinYonekura** [comment]
@mrlajoie , I think you are using an old version of the Exercise2.rmf file, try pulling the file again from github. (I had a similar issue)

**Comment by mrlajoie** [comment]
@LiLinYonekura THANK YOU!

**Comment by mrlajoie** [comment]
Doing the same issue again, even after pulling the file

**Comment by senanu-aggor** [comment]
@mrlajoie - you may still be running the old file. Run the commands in R Studio>Tools>Shell from @LiLinYonekura's post a over week ago again. This should load the latest version from the course repository and your knit html command in ExerciseSet2.Rmd should work.
