### ISSUE TITLE
ExerciseSet2 unable to knit

### ISSUE THREAD

**Issue by mrlajoie** [InseadDataAnalytics/INSEADAnalytics#20]
See following error message
[unable to knit.pdf](https://github.com/InseadDataAnalytics/INSEADAnalytics/files/98384/unable.to.knit.pdf)

**Comment by tevgeniou** [comment]
was the old version. see new one https://github.com/InseadDataAnalytics/INSEADAnalytics/tree/master/Exercises/Exerciseset2
