### ISSUE TITLE
Work with a groceries e-retailer to improve churn prediction

### ISSUE THREAD

**Issue by marcerousseau** [InseadDataAnalytics/INSEADAnalytics#32]
This is a live case where you will work directly on client data provided by the french leader in e-groceries, so be ready!
The goal of the study is to design indicators that predict churn in a non-subscription based business. This is a great opportunity to apply what you learned in a marketing-oriented problem. Interested in tackling this problem ? Build a team and let's get in touch.

**Comment by andertlin** [comment]
We will take it! - Michael D, Amit T, Riya C, and Albert L.
