### ISSUE TITLE
Error: could not find function "gvisTable"

### ISSUE THREAD

**Issue by MeenaMuthuraman** [InseadDataAnalytics/INSEADAnalytics#48]
For Exercise 2, I'm unable to install the above package for R version 3.3.2. Is there anyway around this?

**Comment by NZF85** [comment]
The function works well for me R Version 3.3.1. It could be a version issue where googleVis package hasn't been updated yet

**Comment by tevgeniou** [comment]
try also  source("AnalyticsLibraries/library.R")

**Comment by MeenaMuthuraman** [comment]
I get the same message, ‘AnalyticsLibraries’ is not available (for R version 3.3.2).

**Comment by vkapartzianis** [comment]
You have to source the file, in the "INSEADAnalytics" project. It will install any missing libraries automatically.

![image](https://cloud.githubusercontent.com/assets/1918344/21816990/ea855204-d76a-11e6-8259-3c1c33bae3ec.png)

**Comment by MeenaMuthuraman** [comment]
Thank you, with the above  code, I can see the google Vis package installed under my packages. However, for some reason, the charts still dont print in the HTML doc.

**Comment by vkapartzianis** [comment]
Unfortunately, the latest versions of RStudio seems to have a problem with SSL contexts (which googleVis uses). Please click "Open in Browser" to view the document in your browser.

![image](https://cloud.githubusercontent.com/assets/1918344/21820639/33b33352-d779-11e6-8fc0-fb75e662ad92.png)

Tables and charts should display correctly in all modern browsers:

![image](https://cloud.githubusercontent.com/assets/1918344/21820731/95115638-d779-11e6-8f35-ac16d553751f.png)

**Comment by MeenaMuthuraman** [comment]
Yes, it works, thank you.
