### ISSUE TITLE
Link not working: http://inseaddataanalytics.github.io/INSEADAnalytics/Report_s23.html

### ISSUE THREAD

**Issue by NZF85** [InseadDataAnalytics/INSEADAnalytics#49]
The particular link for exercise 2 is not working to read about principal component analysis. :(

**Comment by tevgeniou** [comment]
this is indeed deleted. it is replaced with this: http://inseaddataanalytics.github.io/INSEADAnalytics/CourseSessions/Sessions23/FactorAnalysisReading.html  

updated and commited to github again. You can get the latest course content from github by "sourcing" the file https://github.com/InseadDataAnalytics/INSEADAnalytics/blob/master/update_fork.R
