### ISSUE TITLE
Cannot commit changes to GitHub repository

### ISSUE THREAD

**Issue by rahulgaur101** [InseadDataAnalytics/INSEADAnalytics#50]
when I try to commit to my GIT repository, I see the following:
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <(null)>) not allowed

I checked the issue page and there are two posts about this error. The posts talk about running a script (with username and email id) in the shell and I don’t understand what that means. Can someone please elaborate? Much appreciate your help.

**Comment by jlkhermes38** [comment]
Hello, your computer needs your github id. In that case (for instance windows) you have to execute 'cmd' or open the Command Prompt Window then to run both lines:
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

![image](https://cloud.githubusercontent.com/assets/7366682/21769064/1f92981a-d67d-11e6-847d-61e5d73806ca.png)

**Comment by rahulgaur101** [comment]
I was trying to do this in the Shell for Rstudio. Will repeat this for the command prompt as well. Thanks a lot for the response

**Comment by jlkhermes38** [comment]
yes, it should be done in the command prompt. please tell me if this works. If it does, you can close the issue. thanks
