### ISSUE TITLE
Files from INSEADAnalytics different from video 7. Shiny and markdown

### ISSUE THREAD

**Issue by YouheeShin** [InseadDataAnalytics/INSEADAnalytics#55]
I have followed 'Video 7 - Shiny and markdown' to import the files from Github to my Rstudio.
However, the files are a bit different from the video - 
For example, in folder session23, there is no folder named 'doc',
but only 'data', and there is no such file named 'report.rmd' as in the video.
Have I imported the wrong files?

**Comment by tevgeniou** [comment]
Indeed, the videos are from an older version of the class. Useful to watch though. the main "getting started instructions" are here:
https://github.com/InseadDataAnalytics/INSEADAnalytics/wiki/Getting-Started 
(Noted as: "You must setup a github account, follow the "Getting Started instructions" to install Rstudio and fork the course github repository before session 1.")

**Comment by tevgeniou** [comment]
so no problem: you have the right files.
