### ISSUE TITLE
Classification analysis - error

### ISSUE THREAD

**Issue by Tommicus** [InseadDataAnalytics/INSEADAnalytics#73]
Quitting from lines 563-567 (GOLDHR.Rmd) 
Error in UseMethod("legend") : 
  no applicable method for 'legend' applied to an object of class "c('double', 'numeric')"

**Comment by vkapartzianis** [comment]
Can you be a bit more specific? Looks like you're trying to use a numeric value where a character one is probably expected.

**Comment by Tommicus** [comment]
Issue resolved
