### ISSUE TITLE
Define a dataseries that does not start from January

### ISSUE THREAD

**Issue by AndreaSiri** [InseadDataAnalytics/INSEADAnalytics#84]
Hi everybody

Do you know how to define a TS that does not start from January?

The code we used in class makes it start from January.
ElectricPrice_ts <- ts(ElectricPriceData$ElectricRate,start=2004, frequency=12)

Thank you,
Andrea

**Comment by sergiobuono** [comment]
Hi Andrea, you can choose the month to start reading your data. Just in the start put: start=c(2010,4).
Hope that helps. 

Sergio

**Comment by AndreaSiri** [comment]
Hey Sergio,

Thank you for the suggestion.
Nonetheless when I try to implement it the console says still it is going to be January (see below).

> tumblr_ts <- ts(tumblr.data$People,start=c(4,2010), frequency=12) # ts function defines the dataset as timeseries starting Jan 2004 and having seasonality of frequency 12 (monthly)

**Comment by sergiobuono** [comment]
It worked here.. in your text the 4 and 2010 are twisted, not sure if it is only this.
